config/routes.rb
Artsready::Application.routes.draw do
  patch "/billing/cancel/(:id)" => "billing#cancel", :as => "billing_cancel"
  get "/billing/get_discount/(:code)" => "billing#get_discount"
  resource :billing, controller: 'billing'

  resources :payment_notifications, only: :create

  get "messages/create"
  get "needs/create"

  get "get_help" => "buddies#get_help", :as => "get_help"
  get "lend_a_hand" => "buddies#lend_a_hand", :as => "lend_a_hand"
  get "buddies" => "buddies#index", :as => "buddies"
  get "buddy(/:id)" => "buddies#show", :as => "buddy"
  get "buddies/profile"

  namespace :admin do
    get "/organizations/billing/(:id)" => "organizations#billing"
    get "/discount_codes/disabled" => "discount_codes#disabled"
    get "/discount_codes/usage" => "discount_codes#usage"
    get "/discount_codes/show_usage/(:id)" => "discount_codes#show_usage"
    patch "/organizations/allow_provisionary_access/(:id)" => "organizations#allow_provisionary_access"
    
    resources :organizations, :only => [:index, :edit, :update, :destroy] do
      resources :users, :only => [:index, :create, :destroy, :edit, :update]
      resources :subscription_events, except: :show
      resource :billing, controller: 'billing', only: [:edit, :update] do
        delete :cancel, on: :member
      end
      get 'billing', on: :member
    end
    resources :users, :only => [:index]
    resources :password_resets, :only => [:create]
    resources :articles, :only => [:update, :destroy, :index]
    resources :comments, :only => [:destroy]
    resources :messages, :only => [:destroy]
    resources :pages, except: [:show]
    resources :templates, only: [:index, :edit, :update]
    resources :questions
    resources :action_items
    resources :discount_codes, except: [:show, :destroy]
    resources :payment_variables
    root :to => 'home#dashboard', :as => "dashboard"
  end

  resources :articles do
    get 'critical_list', :on => :collection
    resources :comments, :only => [:create]
  end
  
  resources :resources
  resources :organizations, :only => [:edit, :update, :show, :new, :create] do
    resources :articles do
      get 'critical_list', :on => :collection
    end
    resources :crises, :only => [:index] do
      member do
        get 'summary'
      end
    end
    resources :battle_buddy_requests, :only => [:create, :show, :index, :update, :destroy]
    resources :messages, :only => [:create]
    resources :users
  end
  
  resources :crises do
    resources :updates
    resources :needs, :only => [:create, :edit, :update]
  end

  resources :archived_assessments, :only => [:index, :show]
  resource :assessment, :only => [:new, :create, :show] do
    resources :sections, :only => [:update]
  end
  resources :answers, :only => [:update] do
    member do
      put 'skip'
      put 'reconsider'
    end
  end
  
  resources :todos
  resources :todo_notes

  get "sign_up" => "organizations#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  get "sign_out" => "sessions#destroy", :as => "sign_out"

  get 'confirm(/:id)' => 'password_resets#edit', :as => :confirmation
  
  resources :users, :only => [:new, :create, :edit, :update, :destroy]
  get "profile" => "users#profile", :as => "profile"
  
  resources :password_resets, :only => [:new, :create, :edit, :update]
  get "member/index", :as => "dashboard"
  get "member/library", :as => "library"

  # public pages
  get "page/:slug" => "pages#show", :as => "page"
  get '/offer' => 'pages#show', :slug => 'afta'

  get "readiness_library" => "home#readiness_library", :as => "readiness_library"
  get "home/public_articles" => "home#public_articles", :as => "public_articles"
  get "home/public_article(/:id)" => "home#public_article", :as => "public_article"
  get "news" => "home#news", :as => "news"
  root :to => "home#index"

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController

  def dashboard
    @crises = Crisis.active
    @expiring = Organization.nearing_expiration
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate!

  def index
    redirect_to dashboard_path if session[:user_id]

    @featured_articles = Article.featured.order('created_at DESC')
    @public_articles = Article.only_public.order('created_at DESC').limit(3)

    @page = Page.find_by_slug('home')
    @page = nil if !@page || @page.body.blank?
  end

  def readiness_library
    @critical_function_counts = Article.for_public.group(:critical_function).count
    @public_articles = Article.for_public
  end

  def public_articles
    if params[:term]
      @public_articles = Article.for_public.matching(params[:term])
    elsif params[:critical_function]
      @public_articles = Article.for_public.with_critical_function(params[:critical_function])
    else
      @public_articles = Article.for_public
    end    
  end

  def public_article
    @article = Article.find(params[:id])
    if !@article.is_public?
      redirect_to :library, :notice => 'That is not a public document.'
    end
  end

  def news
    @page = Page.find_by_slug('news') #rescue OpenStruct(:title => 'Billing', :body => 'Body', :slug => 'Billing')
    render 'pages/show'
  end

end

app/views/home/_search_articles.html.erb
<div id="search-form">
	<%= form_tag public_articles_path, :method => :get  do %>
  <%= text_field_tag :term, '', :class => 'library-search', :placeholder => 'Search articles by title, topic, or tag' %>
  <%= submit_tag 'Search library', :class => 'button green' %>
	<% end %>
</div>  

app/views/home/index.html.erb
<div id="landing">
  <% if @page %>
    <%= raw(@page.body) %>
  <% else %>
    <div class="grid_4">

      <div id="headline">
        <p>
          <b>Create your arts organization's business continuity plan, because
            the
            unexpected, won't-happen-to-me,<br/>I-don't-want-to-think-about-it
            actually <i>does</i> happen.</b></p>

        <p>
          A readiness plan is a combination of documents, processes, policies,
          and
          trainings/drills to build your organization’s sustainability<br/>and
          resilience.
        </p>

        <h1>Be ArtsReady.</h1>
      </div>

      <div id="subhead">
        <h2>What is ArtsReady?</h2>

        <p>ArtsReady, an online emergency preparedness service by and for
          arts/cultural nonprofits, provides arts organizations with customized
          readiness plans for business continuity and post-crisis
          sustainability.
          ArtsReady 2.0 is being rolled out in two phases:
        </p>

        <p>
          <a href="https://www.nedcc.org/free-resources/dplan-the-online-disaster-planning-tool">
            <b>Pocket Response Resource:</b>
          </a>
          Available now, this free customizable emergency document puts critical
          emergency information in the pocket (or device) of staff, crew and
          volunteers, ensuring immediate access to information they’ll need in
          the
          first minutes and hours of any type of emergency. Download your
          customizable template and instructions
          <a href="https://www.nedcc.org/free-resources/dplan-the-online-disaster-planning-tool">here.</a>
        </p>

        <p>
          <b>Online Planning Tool:</b>
          Rolling out in 2021, this
          updated online tool provides a readiness assessment, guidance on
          updating/creating your readiness plan, and Guides and Resources to use
          and adapt for your organization’s customized plan. Your information
          will
          be securely stored, and you will be able to generate reports, training
          documents, templates, plan elements and more. Designed as an annual
          subscription, fee waivers for the first year will be offered.
        </p>

        <p>
          ArtsReady 2.0 also offers
          <a href="https://www.nedcc.org/free-resources/dplan-the-online-disaster-planning-tool/prr-library">
            <b>Guides and Resources,</b>
          </a> an evolving inventory of publications, examples,
          and free resources makes sure you have access to current information
          to
          incorporate into your planning.
        </p>
      </div>
    </div>

    <div class="grid_4">
      <div>
        <h2>Why do readiness planning?</h2>
        <ul class="list-join">
          <li>To be able to get up and running after crisis.</li>
          <li>To protect community and cultural assets.</li>
          <li>To demonstrate sustainability to funders and investors.</li>
          <li>
            To be prepared for any type of crisis, whether within your own
            organization or facility, in your local area, or a widespread
            disaster.
          </li>
        </ul>
      </div>

      <div>

        <p>
          <b>If the Show Can't Go On - Will You Recover?</b><br/>
          <b>Winter Storm Jonas 2016 hits box office hard.</b><br/>
        </p>

        <p>
          As the east coast braced for Winter Storm Jonas the weekend of
          January 22, 2016, presenters and artists with scheduled events
          were likely faced with the questions, “What is our cancellation
          policy? Are we ready to put it into action? And can we survive
          the possible financial impact?” Those with clear cancellation
          plans almost certainly found ease from the stress of having to
          create one off the cuff, and only needed to take on the task of
          implementing it, giving them a jump start on the ultimate goal
          of mitigating losses.
          <a href="https://www.artsready.org/home/public_article/821">
            Read more…
          </a>
        </p>
      </div>
    </div>
  <% end %>
  <div class="grid_4">
    <%= link_to page_path('get_arts_ready') do %>
      <div id="dont-risk-it">
        <h1>Don't risk it.</h1>

        <p><span class="linklike">Sign up</span> to
          <i>start protecting your organization!</i></p>
      </div>
    <% end %>
    <section>
      <h2>Partners</h2>
      <p>
        ArtsReady works in partnership with these organizations to provide free
        resources and training for arts organizations and artists to increase
        their readiness, as well as respond and recover from crises.
      </p>
      <ul>
        <li>
          <a href="https://www.nedcc.org/free-resources/dplan-the-online-disaster-planning-tool">
            dPlan/ArtsReady 2.0
          </a>
          is a partnership of South Arts and NEDCC
        </li>
        <li>
          <a href="https://ncaper.org/">
            NCAPER – National Coalition for Arts’
            Preparedness and
            Emergency Response
          </a>
        </li>
        <li>
          <a href="https://cerfplus.org/">CERF+/The Artists Safety Net</a>
        </li>
        <li>
          <a href="https://performingartsreadiness.org/">
            Performing Arts Readiness,
          </a>
          a community served by LYRASIS. The PAR
          project is made possible through generous support from the Andrew W.
          Mellon Foundation.
        </li>
      </ul>
    </section>
  </div>
</div>

app/views/home/library.html.erb
<div class="grid_12">
  <section>
    <div class="grid_8 alpha">
      <h1>Readiness Library</h1>
      <%= text_field_tag :search, '', :class => 'library-search', :placeholder => 'Search articles by title, topic, or tag' %>
      <%= link_to 'search library', "", :class => 'button green' %>
    </div>
    <div class="grid_4 omega">
      <h3>About the Library</h3>
      <p>
        <%= image_tag('library-video.png', :style => 'float: left; margin-right: 10px; margin-bottom: 10px; border: 1px solid #ccc;') %>
        This is a collection of resources (articles, documents, uploads) that can be useful when planning your organization's readiness...
      </p>
    </div>
    <div class="clear"></div>
  </section>
  <div class="grid_4 alpha">
    <h3>Topics</h3>
    <ul class="library categories">
      <% ArtsreadyDomain::CRITICAL_FUNCTIONS.each do |function| %>
        <li><%= link_to "#{function[:title]} (#{rand(100) + 10})" %></li>
      <% end %>
    </ul>
  </div>
  <div class="grid_4">
    <h3>Popular Articles</h3>
    <ul class="library popular">
      <% Article.featured.each do |article| %>
        <li>
          <h4><%= link_to article.title, article_path(article) %></h4>
          Added by Jim Johnson on <%= article.published_on.to_formatted_s(:long) %>
        </li>
      <% end %>
    </ul>

    <ul class="tag-cloud">
      <li><a href="#" class="size-1">this</a></li>
      <li><a href="#" class="size-4">is a</a></li>
      <li><a href="#" class="size-3">tag cloud</a></li>
      <li><a href="#" class="size-6">crisis</a></li>
      <li><a href="#" class="size-3">flooding</a></li>
      <li><a href="#" class="size-2">fire</a></li>
      <li><a href="#" class="size-1">tornado</a></li>
      <li><a href="#" class="size-5">hurricane</a></li>
      <li><a href="#" class="size-3">fraud</a></li>
      <li><a href="#" class="size-6">riot</a></li>
      <li><a href="#" class="size-5">act of god</a></li>
      <li><a href="#" class="size-6">rodentia</a></li>
      <li><a href="#" class="size-3">labor</a></li>
    </ul>
  </div>
  <div class="grid_4 omega">
    <section>
      <h3>Recent Comments</h3>
      <ul class="library">
        <% 3.times do %>
          <li>
            <i><%= image_tag('library-comment.png', :style => 'float: left; margin-right: 10px; margin-bottom: 10px;') %>
            Thanks so much for this! I do have a question about...</i><br />
            <%= link_to "An article's title", '/wireframe/kb' %> <%= pluralize(rand(4) + 1, 'hour') %> ago
          </li>
        <% end %>
      </ul>
    </section>
    <section>
      <h3>Share Your Knowledge</h3>
      <p style="padding:10px; margin:0;"><%= link_to 'submit article', new_article_path, :class => 'button' %></p>
    </section>
  </div>
</div>

app/views/home/public_article.html.erb
<div class="grid_12">
  <hgroup>
    <h1>Article</h1>
    <h2><%= @article.title %></h2>
  </hgroup>
</div>

<div class="grid_8">
  <%= render 'articles/article' %>  
</div>
<div class="grid_4">
  <%= render 'articles/sidebar', :locals => {:article => @article} %>
</div>

app/views/home/public_articles.html.erb
<div class="grid_12">
  <h1>Library</h1>
	<%= render 'search_articles' %>
	<hr>
    <section>
      <table class="articles">
        <thead>
          <tr>
            <th><p>Title</p></th>
            <th><p>Description</p></th>
            <th><p>Type</p></th>
            <th><p>Critical Function</p></th>
            <th><p>Tags</p></th>
          </tr>
        </thead>
        <tbody>
          <% @public_articles.each do |a| %>
            <tr>
              <td class="title"><p><%= link_to a.title, public_article_path(a) %></p></td>
              <td class="description"><p><%= a.description %></p></td>
              <td class="source"><p>
                <% if a.link.present? %>
                <%= link_to 'Visit', a.link, :target => '_blank' %>
                <% elsif a.document.present? %>
                <%= link_to "Download", a.document.url, :target => '_blank' %>
                <% else %>
                <%= link_to 'Read', article_path(a) %>
                <% end %>
              </p></td>
              <td class="function"><p>
                <%= link_to a.critical_function.capitalize, 
                      public_articles_path(
                        :critical_function => a.critical_function)
                %>
              </p></td>
              <td class="tags"><p><%= a.tag_list.to_s %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$(".articles").tablesorter();
	})
</script>

app/views/home/readiness_library.html.erb
<div class="grid_12">
  <section>
    <div class="grid_8 alpha">
      <h1>Readiness Library</h1>
    	<%= render 'search_articles' %>
		</div>
    <div class="grid_4 omega">
      <h3>About the Library</h3>
      <p>This is a collection of resources (articles, documents, uploads) that can be useful when planning your organization's readiness...</p>
    </div>
    <div class="clear"></div>
  </section>
  <div class="grid_4 alpha">
    <h3>Topics</h3>
    <ul class="library categories">
      <% ArtsreadyDomain::LIBRARY_TOPICS.each do |function| %>
        <li><%= link_to "#{function[:title]} (#{@critical_function_counts[function[:name]] rescue 0})", public_articles_path(:critical_function => function[:name]) %></li>
      <% end %>
    </ul>
  </div>
  <div class="grid_4">
    <h3>Featured Articles</h3>
    <ul class="library popular">
      <% Article.featured.each do |article| %>
        <li>
          <h4><%= link_to article.title, public_article_path(article) %></h4>
          Added by <%= article.user_name %> on <%= article.published_on.to_formatted_s(:long) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="grid_4 omega"></div>
</div>