config/routes.rb
Artsready::Application.routes.draw do
  patch "/billing/cancel/(:id)" => "billing#cancel", :as => "billing_cancel"
  get "/billing/get_discount/(:code)" => "billing#get_discount"
  resource :billing, controller: 'billing'

  resources :payment_notifications, only: :create

  get "messages/create"
  get "needs/create"

  get "get_help" => "buddies#get_help", :as => "get_help"
  get "lend_a_hand" => "buddies#lend_a_hand", :as => "lend_a_hand"
  get "buddies" => "buddies#index", :as => "buddies"
  get "buddy(/:id)" => "buddies#show", :as => "buddy"
  get "buddies/profile"

  namespace :admin do
    get "/organizations/billing/(:id)" => "organizations#billing"
    get "/discount_codes/disabled" => "discount_codes#disabled"
    get "/discount_codes/usage" => "discount_codes#usage"
    get "/discount_codes/show_usage/(:id)" => "discount_codes#show_usage"
    patch "/organizations/allow_provisionary_access/(:id)" => "organizations#allow_provisionary_access"
    
    resources :organizations, :only => [:index, :edit, :update, :destroy] do
      resources :users, :only => [:index, :create, :destroy, :edit, :update]
      resources :subscription_events, except: :show
      resource :billing, controller: 'billing', only: [:edit, :update] do
        delete :cancel, on: :member
      end
      get 'billing', on: :member
    end
    resources :users, :only => [:index]
    resources :password_resets, :only => [:create]
    resources :articles, :only => [:update, :destroy, :index]
    resources :comments, :only => [:destroy]
    resources :messages, :only => [:destroy]
    resources :pages, except: [:show]
    resources :templates, only: [:index, :edit, :update]
    resources :questions
    resources :action_items
    resources :discount_codes, except: [:show, :destroy]
    resources :payment_variables
    root :to => 'home#dashboard', :as => "dashboard"
  end

  resources :articles do
    get 'critical_list', :on => :collection
    resources :comments, :only => [:create]
  end
  
  resources :resources
  resources :organizations, :only => [:edit, :update, :show, :new, :create] do
    resources :articles do
      get 'critical_list', :on => :collection
    end
    resources :crises, :only => [:index] do
      member do
        get 'summary'
      end
    end
    resources :battle_buddy_requests, :only => [:create, :show, :index, :update, :destroy]
    resources :messages, :only => [:create]
    resources :users
  end
  
  resources :crises do
    resources :updates
    resources :needs, :only => [:create, :edit, :update]
  end

  resources :archived_assessments, :only => [:index, :show]
  resource :assessment, :only => [:new, :create, :show] do
    resources :sections, :only => [:update]
  end
  resources :answers, :only => [:update] do
    member do
      put 'skip'
      put 'reconsider'
    end
  end
  
  resources :todos
  resources :todo_notes

  get "sign_up" => "organizations#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  get "sign_out" => "sessions#destroy", :as => "sign_out"

  get 'confirm(/:id)' => 'password_resets#edit', :as => :confirmation
  
  resources :users, :only => [:new, :create, :edit, :update, :destroy]
  get "profile" => "users#profile", :as => "profile"
  
  resources :password_resets, :only => [:new, :create, :edit, :update]
  get "member/index", :as => "dashboard"
  get "member/library", :as => "library"

  # public pages
  get "page/:slug" => "pages#show", :as => "page"
  get '/offer' => 'pages#show', :slug => 'afta'

  get "readiness_library" => "home#readiness_library", :as => "readiness_library"
  get "home/public_articles" => "home#public_articles", :as => "public_articles"
  get "home/public_article(/:id)" => "home#public_article", :as => "public_article"
  get "news" => "home#news", :as => "news"
  root :to => "home#index"

end

app/controllers/crises_controller.rb
class CrisesController < ApplicationController

  def index
    @crises = current_org.crises.resolved.order('resolved_on DESC')
  end
  
  def new
    @crisis = current_org.crises.build(:user_id => current_user.id)
    @crisis.visibility = 'public' if current_org.battle_buddies.empty?
  end
  
  def edit
    @crisis = current_org.crisis
  end

  def show
    @crisis = Crisis.find(params[:id])
  end
  
  def summary
    @crisis = current_org.crises.find(params[:id])
  end

  def update
    #TODO fix this hack
    if params[:buddy_list].present?
      buddy_list = params[:buddy_list].collect {|i| i.to_i}.join(',')
      params[:crisis].merge!(:buddy_list => buddy_list)
    end
    if @current_org.crisis.update_attributes(crisis_params)
      redirect_to crisis_path(current_org.crisis), :notice => "Crisis updated"
    else
      redirect_to crisis_path(current_org.crisis), :notice => "Problem updating your crisis"
    end
  end
  
  def create
    #TODO fix this hack
    if params[:buddy_list].present?
      buddy_list = params[:buddy_list].collect {|i| i.to_i}.join(',')
      params[:crisis].merge!(:buddy_list => buddy_list)
    end
    @crisis = current_org.crises.create(crisis_params)
    @crisis.user = current_user
    if @crisis.save
      redirect_to dashboard_path, :notice => 'Crisis declared!'
    else
      render :action => "new"
    end
  end

  def destroy
    if current_org.crisis.resolve_crisis!
      redirect_to dashboard_path, :notice => 'Crisis resolved!'
    else
      redirect_to dashboard_path, :notice => 'Crisis could not be resolved'
    end
  end

  private

  def crisis_params
    params.require(:crisis).permit(
      :description,
      :visibility,
      buddy_list: []
    )
  end

end

app/views/crises/_need.html.erb
<tr class="show">
  <td class="resource">
    <p><%= need.resource %></p>
  </td>
  <td class="description">
    <p><%= need.description %></p>
  </td>
  <td class="status">
    <p><%= need.status %></p>
  </td>
  <td class="provider">
    <p><%= need.provider %></p>
  </td>
  <td class="activity">
    <p><%= need.updated_at %></p>
  </td>
  <td>
    <p>
      <%= link_to "Edit", edit_crisis_need_path(current_org.crisis,need) unless need.crisis.resolved?%>
      <%#= button_to_function 'Edit', "$(this).parents('tr.show').toggle(); $(this).parents('tr.show').next('tr.edit').toggle();", :class => 'button white' %>
    </p>
  </td>
</tr>

app/views/crises/_update.html.erb
<tr>
  <td class="badge">
    <span class="date"><%= update.created_at.strftime("%D") %></span>
  </td>
  <td class="from">
    <h5><%= update.user_name %></h5>
    <%= link_to update.organization_name, buddy_path(update.organization) %>
  </td>
  <td class="body">
    <div class="less">
      <%= update.message %>
    </div>
  </td>
</tr>

app/views/crises/edit.html.erb
<div class="grid_6">
  <div id="declare-crisis-form">
    <h3>Edit a Crisis</h3>
    <%= form_for(@crisis) do |f|%>
    <div id="crisis-visibility">
    <%= f.label :visibility, 'Crisis Visibility' %>
    <%= f.radio_button :visibility, 'public' %> Public <br   />
    <%= f.radio_button :visibility, 'buddies' %> All Battle Buddies <br />
    <%= f.radio_button :visibility, 'private' %> Private/Allow Specific Battle Buddies<br />
    <div id="battle-buddies-list" style="display:none;">
      <% current_org.battle_buddies.each do |buddy| %>
      <%= check_box_tag "buddy_list[]", buddy.id, (@crisis.buddy_list.split(',').include?(buddy.id.to_s) ? true : false rescue false) %><%= buddy.name %><br />
      <% end %>
    </div>
    </div>
    <%= f.submit "Update Crisis" %> 
    <% end %>
  </div>
</div>

app/views/crises/index.html.erb
<div class="grid_12">
  <h1>Previous Crises</h1>
  <%= render :partial => '/shared/settings_navbar', :locals => {:current_settings_tab => :previous_crises} %>
	<hr>
    <section>
      <table class="resource side-nav-panels">
        <thead>
          <td><p>Declared on</p></td>
          <td><p>Resolved on</p></td>
          <td><p>Privacy</p></td>
          <td><p>Description</p></td>
        </thead>
        <tbody>
          <% @crises.each do |crisis| %>
            <tr>
              <td class="title"><p><%= link_to crisis.created_at, summary_organization_crisis_path(current_org,crisis) %></p></td>
              <td class="description"><p><%= crisis.resolved_on %></p></td>
              <td class="function"><p><%= crisis.visibility.humanize %></p></td>
              <td class="description"><p><%= crisis.description %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
</div>

app/views/crises/new.html.erb
<div class="grid_6">
  <div id="declare-crisis-form">
    <h3>Declare a Crisis</h3>
    <%= form_for(@crisis) do |f|%>
      <%= f.error_messages %>
      <%= f.label :description %>
      <%= f.text_area :description, :size => '20x5' %>
      <div id="crisis-visibility">
        <%= f.label :visibility, 'Crisis Visibility' %>
        <%= f.radio_button :visibility, 'public'%> Public <br />
        <% if current_org.battle_buddies.present? %>
          <%= f.radio_button :visibility, 'buddies' %> All Battle Buddies <br />        
          <%= f.radio_button :visibility, 'private' %> Private/Allow Specific Battle Buddies<br />
        <% else %>
          <div class="crisis_advice">
            <p>If you don't want to declare this crisis publicly, you might want to develop a network of specific organizations to help you.</p>
            <p><%= link_to('Find some Battle Buddies', get_help_path, :class => 'button') %></p>        
            <p>If you would like advice or support, please contact your subsidizing service organization, or the ArtsReady Team (admin@artsready.org, 404-874-7244 x29 or x13).</p>
          </div>
        <% end %>
        <div id="battle-buddies-list">
          <% current_org.battle_buddies.each do |buddy| %>
          <%= check_box_tag "buddy_list[]", buddy.id, false %><%= buddy.name %><br />
          <% end %>
        </div>
      </div>
      <%= f.submit "Declare Crisis" %> <%= link_to 'Cancel', dashboard_path, :class => 'button green' %>
    <% end %>
  </div>
</div>

app/views/crises/show.html.erb
<div class="grid_8" style="margin-bottom:20px;">
  <h1>Battle Buddy Network</h1>
</div>
<div class="grid_4 alpha">
  <div style="margin-left:20px">
  <%= render :partial => '/shared/crisis_switch', :locals => {:float => 'left'} %>
  </div>
</div>

<div class="grid_12 alpha">
  <%= render :partial => '/shared/bbn_navbar', :locals => {:current_bbn_tab => :crisis_console} %>
</div>

<div class="grid_12">
  <section>
    <h2>Crisis Description</h2>
    <p>Privacy: <%= current_org.crisis.visibility.humanize %> <%= link_to "Edit", edit_crisis_path(current_org.crisis) %></p>
    <p><%= current_org.crisis.description %></p>
    <p>Declared by <%= current_org.crisis.user_name %> on <%= current_org.crisis.created_at.to_date %></p>
  </section>
  <section>
    <h2 class="buddy">Your Needs</h2>
    <table class="needs">
      <thead>
        <td><p>Resource</p></td>
        <td><p>Description</p></td>
        <td><p>Status</p></td>
        <td><p>Provider</p></td>
        <td><p>Activity</p></td>
        <td><p></p></td>
      </thead>
      <tbody>
        <%= render :partial => 'need', :collection => current_org.crisis.needs %>
      </tbody>
    </table>
  </section>
   <section>
      <table class="add-need">
        <thead>
          <td colspan="7"><p>Add a need</p></td>
        </thead>
        <tbody>
        <%= form_for([current_org.crisis,Need.new]) do |f| %>
            <tr>
              <td class="resource"><p><%= f.text_field :resource, :placeholder => 'Resource request' %></p></td>
              <td class="description"><p><%= f.text_field :description, :placeholder => 'Description' %></td>
              <td class="add-button"><p><%= f.submit 'Add', :class => 'button add-need-button' %></p></td>
            </tr>
        <% end %>
        </tbody>
      </table>
  </section>
  <section>
    <h2 class="buddy">Crisis Log</h2>
    <div id="crisis-update" style="margin-bottom: 20px;">
      <%= form_for([current_org.crisis,Update.new]) do |f| %>
      <div class="grid_10 alpha">
        <%= f.text_area :message, :rows => 2, :placeholder => 'Send crisis update' %>
      </div>
      <div class="grid_2 omega">
        <%= f.submit 'Report', :class => 'button blue' %>
        <br />Select to send this message.
      </div>
      <% end %>
      <div class="clear"></div>
    </div>
    <table id="messages">
      <%= render :partial => 'update', :collection => current_org.crisis.updates.order("created_at DESC") %>
    </table>
  </section>

</div>

app/views/crises/summary.html.erb
<div class="grid_12">
  <h1>Crisis Summary</h1>
  <section>
    <h2>Crisis Description</h2>
    <p>Resolved on <%= @crisis.resolved_on.to_date %></p>
    <p>Privacy: <%= @crisis.visibility.humanize %></p>
    <p><%= @crisis.description %></p>
    <p>Declared by <%= @crisis.user_name %> on <%= @crisis.created_at.to_date %></p>
  </section>
  <section>
    <h2 class="buddy">Your Needs</h2>
    <table class="needs">
      <thead>
        <td><p>Resource</p></td>
        <td><p>Description</p></td>
        <td><p>Status</p></td>
        <td><p>Provider</p></td>
        <td><p>Activity</p></td>
        <td><p></p></td>
      </thead>
      <tbody>
        <%= render :partial => 'need', :collection => @crisis.needs %>
      </tbody>
    </table>
  </section>
  <section>
    <h2 class="buddy">Crisis Log</h2>
    <table id="messages">
      <%= render :partial => 'update', :collection => @crisis.updates.order("created_at DESC") %>
    </table>
  </section>
</div>