config/routes.rb
Artsready::Application.routes.draw do
  patch "/billing/cancel/(:id)" => "billing#cancel", :as => "billing_cancel"
  get "/billing/get_discount/(:code)" => "billing#get_discount"
  resource :billing, controller: 'billing'

  resources :payment_notifications, only: :create

  get "messages/create"
  get "needs/create"

  get "get_help" => "buddies#get_help", :as => "get_help"
  get "lend_a_hand" => "buddies#lend_a_hand", :as => "lend_a_hand"
  get "buddies" => "buddies#index", :as => "buddies"
  get "buddy(/:id)" => "buddies#show", :as => "buddy"
  get "buddies/profile"

  namespace :admin do
    get "/organizations/billing/(:id)" => "organizations#billing"
    get "/discount_codes/disabled" => "discount_codes#disabled"
    get "/discount_codes/usage" => "discount_codes#usage"
    get "/discount_codes/show_usage/(:id)" => "discount_codes#show_usage"
    patch "/organizations/allow_provisionary_access/(:id)" => "organizations#allow_provisionary_access"
    
    resources :organizations, :only => [:index, :edit, :update, :destroy] do
      resources :users, :only => [:index, :create, :destroy, :edit, :update]
      resources :subscription_events, except: :show
      resource :billing, controller: 'billing', only: [:edit, :update] do
        delete :cancel, on: :member
      end
      get 'billing', on: :member
    end
    resources :users, :only => [:index]
    resources :password_resets, :only => [:create]
    resources :articles, :only => [:update, :destroy, :index]
    resources :comments, :only => [:destroy]
    resources :messages, :only => [:destroy]
    resources :pages, except: [:show]
    resources :templates, only: [:index, :edit, :update]
    resources :questions
    resources :action_items
    resources :discount_codes, except: [:show, :destroy]
    resources :payment_variables
    root :to => 'home#dashboard', :as => "dashboard"
  end

  resources :articles do
    get 'critical_list', :on => :collection
    resources :comments, :only => [:create]
  end
  
  resources :resources
  resources :organizations, :only => [:edit, :update, :show, :new, :create] do
    resources :articles do
      get 'critical_list', :on => :collection
    end
    resources :crises, :only => [:index] do
      member do
        get 'summary'
      end
    end
    resources :battle_buddy_requests, :only => [:create, :show, :index, :update, :destroy]
    resources :messages, :only => [:create]
    resources :users
  end
  
  resources :crises do
    resources :updates
    resources :needs, :only => [:create, :edit, :update]
  end

  resources :archived_assessments, :only => [:index, :show]
  resource :assessment, :only => [:new, :create, :show] do
    resources :sections, :only => [:update]
  end
  resources :answers, :only => [:update] do
    member do
      put 'skip'
      put 'reconsider'
    end
  end
  
  resources :todos
  resources :todo_notes

  get "sign_up" => "organizations#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  get "sign_out" => "sessions#destroy", :as => "sign_out"

  get 'confirm(/:id)' => 'password_resets#edit', :as => :confirmation
  
  resources :users, :only => [:new, :create, :edit, :update, :destroy]
  get "profile" => "users#profile", :as => "profile"
  
  resources :password_resets, :only => [:new, :create, :edit, :update]
  get "member/index", :as => "dashboard"
  get "member/library", :as => "library"

  # public pages
  get "page/:slug" => "pages#show", :as => "page"
  get '/offer' => 'pages#show', :slug => 'afta'

  get "readiness_library" => "home#readiness_library", :as => "readiness_library"
  get "home/public_articles" => "home#public_articles", :as => "public_articles"
  get "home/public_article(/:id)" => "home#public_article", :as => "public_article"
  get "news" => "home#news", :as => "news"
  root :to => "home#index"

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include Gmaps4rails::ActsAsGmappable
  acts_as_gmappable validation: false
  geocoded_by :full_street_address

  has_one :assessment, -> { order('created_at DESC') }, :dependent => :destroy
  has_many :assessments, :dependent => :destroy
  has_one :crisis, -> { where("resolved_on IS NULL") } #TODO ensure there is only one, and maybe sort by latest date as a hack
  has_many :articles
  has_many :public_articles, -> { where("visibility = 'public'") },
    :class_name => 'Article',
    :dependent => :nullify
  has_many :non_public_articles, -> { where("visibility <> 'public'") },
    :class_name => 'Article',
    :dependent => :destroy
  has_many :comments, :through => :articles
  has_many :battle_buddy_requests, :dependent => :destroy
  has_many :battle_buddies,
    -> { where(:battle_buddy_requests => {:accepted => true}) },
    :through => :battle_buddy_requests
  has_many :battle_buddy_requests_received, -> { where("battle_buddy_requests.accepted IS NOT true") }, :class_name => 'BattleBuddyRequest', :foreign_key => 'battle_buddy_id'
  has_many :battle_buddy_requests_sent, -> { where("battle_buddy_requests.accepted IS NOT true") }, :class_name => 'BattleBuddyRequest'
  has_many :crises, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :resources, :dependent => :destroy
  has_many :todos, :dependent => :destroy
  has_many :updates, :dependent => :destroy
  has_many :users, :dependent => :destroy
  has_many :managers, -> { where("users.role = 'manager'") }, :class_name => 'User'
  has_many :executives, -> { where("users.role = 'executive'") }, :class_name => 'User'
  has_many :editors, -> { where("users.role = 'editor'") }, :class_name => 'User'
  has_many :readers, -> { where("users.role = 'reader'") }, :class_name => 'User'
  has_many :subscriptions, -> { order(:start_date) }
  has_one :active_subscription, -> { where(subscriptions: {active: true}) },
    class_name: 'Subscription'
  has_many :subscription_events
  has_many :payments, -> { order('subscription_events.happened_at ASC') },
    through: :subscription_events

  accepts_nested_attributes_for :users

  validates_presence_of :name, :address, :city, :state, :zipcode, :organizational_status

  # disabled as app approaches EOL
  # after_validation :geocode, :if => lambda{ |obj| (obj.changed.include?("address") || obj.changed.include?("city") || obj.changed.include?("state") || obj.changed.include?("zipcode"))  }

  after_create :send_admin_notification
  after_update :send_approval_email, :if => lambda{ |obj| (obj.changed.include?("active") && obj.active?)  }
  after_update :setup_initial_todo, :if => lambda{ |obj| (obj.changed.include?("active") && obj.active?)  }

  # disabled as app approaches EOL
  # after_save :update_salesforce

  scope :active, -> { where(:active => true) }
  scope :in_buddy_network, -> { where(:battle_buddy_enabled => true) }
  scope :to_approve, -> { where(:active => false) }
  scope :nearing_expiration, -> { where('0=1') }
  scope :in_crisis, -> { includes(:crisis).where('crises.resolved_on IS NULL') }
  scope :billing_next_month, -> {
    next_month = Time.zone.today + 1.month

    where("next_billing_date BETWEEN ? and ?",
      next_month.beginning_of_month,
      next_month.end_of_month
    )
  }
  scope :renewing_in, lambda { |days|
    active.where(next_billing_date: Time.zone.today + days)
  }
  scope :credit_card_expiring_this_month, -> {
    active.
      joins(:active_subscription).
      merge(Subscription.credit_card_expiring_this_month)
  }

  delegate :complete?, :to => :assessment, :allow_nil => true, :prefix => true
  delegate :percentage_complete, :to => :assessment, :allow_nil => true, :prefix => true
  delegate :billing_first_name, :billing_last_name,
    :billing_address, :billing_city, :billing_state, :billing_zipcode,
    :payment_method, :payment_number,
    :discount_code, :next_billing_amount,
    to: :subscription, allow_nil: true
  delegate :identifier, to: :discount_code, prefix: true, allow_nil: true

  def self.with_user_activity_since(last=1.week.ago)
    active.select('DISTINCT organizations.id').joins(:users).where('users.last_login_at > ?',last)
  end
  
  def self.activity_percentage(last=1.week.ago)
    ((Organization.with_user_activity_since(last).count.to_f / Organization.active.count.to_f)*100).to_i rescue 0
  end

  def contact_first_name
    split_name(contact_name).first
  end

  def contact_last_name
    split_name(contact_name).last
  end

  def split_name(name)
    return [nil, nil] if name.blank?

    name = name.split(/,/, 2).first # remove honorifics
    words = name.split(/\s+/)
    [words[0..-2].join(' '), words[-1]].map(&:presence)
  end

  def full_street_address
    [address, city, state, zipcode].compact.join(', ')
  end

  def gmaps4rails_address
    full_street_address
  end

  def deletable?
    # must deactivate an organization before deleting it
    !active? && users.all?(&:disabled?)
  end
    
  def battle_buddy_list
    battle_buddies.collect(&:id).uniq
  end

  def battle_buddy_request_for(buddy)
    battle_buddy_requests.find_by_battle_buddy_id(buddy)
  end

  def last_activity
    users.order('last_login_at DESC').first.try(:last_activity)
  end

  def declared_crisis?
    crises.where(:resolved_on => nil).count == 1 ? true : false
  end

  def todo_percentage_complete
    ((todos.completed.count.to_f / todos.count.to_f)*100).to_i rescue 0
  end
  
  def build_provisional_subscription
    ProvisionalSubscription.new(organization: self)
  end

  def active_subscription_end_date
    return nil if !self.subscription || !self.subscription.active?
    return next_billing_date
  end

  def first_billing_date
    first_subscription.start_date.to_date if first_subscription
  end

  def first_billing_amount
    first_subscription.starting_amount if first_subscription
  end

  def first_subscription
    subscriptions.order('created_at ASC').first
  end

  def latest_billing_amount
    payments.last.try(:amount)
  end

  def subscription
    subscriptions.last
  end

  def status
    @status ||= OrganizationStatus.new(self, subscription)
  end

  def billing_emails
    subscription.try(:billing_email).presence || executives.pluck(:email)
  end

  def days_left_until_rebill
    (next_billing_date - Time.zone.today).to_i if next_billing_date
  end

  def extend_next_billing_date!
    update_attribute(:next_billing_date, extended_next_billing_date)
  end

  def extended_next_billing_date
    (next_billing_date ? next_billing_date : Time.zone.today) + 365
  end

  def payment_method_expired?
    active_subscription &&
      active_subscription.payment_method_expires_before?(Time.zone.now.to_date)
  end

  def payment_method_expires_before_next_billing_date?
    next_billing_date &&
      active_subscription &&
      active_subscription.payment_method_expires_before?(next_billing_date)
  end

  def account_status
    active ? 'active' : (subscription ? 'inactive' : 'needs approval')
  end

  def cancel_subscriptions(options)
    subscriptions.active.where('id <> ?', options[:except]).
      find_each(&:cancel)
  end

  def create_subscription_event(attrs)
    subscription_events.create(attrs)
  end

  def self.send_renewal_reminders
    [30, 15].each do |days|
      renewing_in(days).find_each do |org|
        org.send_renewal_reminder
      end
    end
  end

  def send_renewal_reminder
    BillingMailer.renewal_reminder(self).deliver_now
  end

  def self.send_credit_card_expiration_notices
    credit_card_expiring_this_month.find_each do |org|
      org.send_credit_card_expiration_notice
    end
  end

  def send_credit_card_expiration_notice
    BillingMailer.credit_card_expiration(self).deliver_now
  end

  def update_salesforce
    SalesforceClient.new.upsert_account(self)
  end

  private
   
  def send_admin_notification
    logger.debug("Sending sign_up email for organization #{name}")
    User.admins.each do |admin|
      logger.debug("Trying to send to #{admin.email}")
      AdminMailer.new_organization(self,admin).deliver_now rescue logger.debug("send org notification to admin email failed")
    end
  end

  def send_approval_email
    logger.debug("Sending approval email for organization #{name}")
    OrganizationMailer.approved(self).deliver_now rescue logger.debug("send approval email failed")
  end
  
  def setup_initial_todo
    logger.debug("setup_initial_todo: #{self.todos.count}")
    self.todos.create(:critical_function => 'people', :description => "adding a second manager through the Settings menu to ensure your organization's access to the ArtsReady site", :priority => 'critical', :user => users.first, :due_on => Time.zone.today) if self.todos.count == 0
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::AdminController

  def index
    @organizations = Organization.all
  end
  
  def edit
    @organization = Organization.find(params[:id])
  end
  
  def update
    @organization = Organization.find(params[:id])

    if @organization.update_attributes(params[:organization])
      redirect_to admin_organizations_path, :notice => "Organization updated"
    else
      redirect_to admin_organizations_path, :notice => "Problem updating organization"
    end

  end
  
  def billing
    @organization = Organization.find(params[:id])
    @subscription = @organization.subscription
  end
  
  def allow_provisionary_access
    @organization = Organization.find(params[:id])
    @subscription = @organization.build_provisional_subscription

    if @subscription.save
      redirect_to :back, :notice => "Provisional access has been granted"
    else
      redirect_to :back, :notice => "Problem granting access."
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    if @organization.deletable?
      @organization.destroy
      redirect_to(admin_organizations_path, :notice => 'Organization was successfully destroyed.')
    else
      logger.warn("Admin had trouble destroying #{@organization.name}")
      redirect_to(admin_organizations_path, :notice => 'Problem destroying org')
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  skip_before_filter :authenticate!, :only => [:new, :create]

  def new
    @organization = Organization.new
  end
  
  def create
    user = params[:organization][:users_attributes]['0']
    logger.debug(user.inspect)
    params[:organization].merge!({:contact_name => "#{user[:first_name]} #{user[:last_name]}", :email => user[:email]})
    logger.debug(params[:organization].inspect)
    @organization = Organization.new(organization_params)
    if @organization.save
      session[:user_id] = User.find_by_email(user[:email]).id
      redirect_to new_billing_path, :notice => "Signed up!"
    else
      render "new"
    end    
  end
  
  def edit
    @organization = current_org
  end

  def update
    @organization = current_org

    if @organization.update_attributes(organization_params)
      redirect_to edit_organization_path(current_org), :notice => 'Organization was successfully updated.'
    else
      render 'edit'
    end

  end

  private

  def organization_params
    params.require(:organization).permit(
      :name, :address, :address_additional, :city, :state, :zipcode,
      :email, :phone_number, :fax_number, :contact_name,
      :parent_organization, :subsidizing_organization, :organizational_status,
      :nsic_code, :other_nsic_code,
      :battle_buddy_enabled,
      users_attributes: [
        :first_name, :last_name, :title, :email,
        :password, :password_confirmation,
        :accepted_terms
      ]
    )
  end
end

app/views/admin/organizations/billing.html.erb
<%= render 'admin/shared/organization_header' %>

<div class="grid_8 admin-actions">
  <%= render 'admin/shared/organization_actions' %>
</div>

<div class="grid_12">
  <%= render 'admin/shared/organization_menu' %>
</div>

<div class="grid_8">
  <section class="billing_info">
    <h3>Billing Information:</h3>
    <%= render 'shared/account_status' %>

    <% if @subscription && @subscription.active? %>
      <%= render 'shared/billing_info' %>

      <% code = @subscription.discount_code %>
      <% if code %>
        <p>
          Discount code:
          <%= link_to code.discount_code, [:edit, :admin, code] %>
        </p>
      <% end %>
    <% elsif @organization.next_billing_date %>
      <p>
        Next billing date:
        <%= @organization.next_billing_date.try(:strftime, "%B %d, %Y") %>
        (<%= pluralize @organization.days_left_until_rebill, 'day' %>)
      </p>
    <% else %>
      <p>
        This organization has not set up their billing yet!
        <%= link_to "Allow provisional access for 1 year",
          "/admin/organizations/allow_provisionary_access/#{@organization.id}",
          method: :patch
        %>
      </p>

    <% end %>

    <% unless @organization.subscriptions.empty? %>
      <h3>Subscription History:</h3>
      <table id="subscription_log">
        <thead>
          <tr>
            <th>Subscription ID</th>
            <th>Start Date</th>
            <th>Status</th>
          </tr>
        </thead>

        <tbody>
          <% @organization.subscriptions.reverse.each do |sub| %>
            <tr>
              <td><p><%= sub.arb_id %></p></td>
              <td><p><%= sub.start_date.try(:strftime, "%m/%d/%Y") %></p></td>
              <td><p><%= sub.active? ? 'Active' : 'Inactive' %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </section>
</div>

app/views/admin/organizations/edit.html.erb
<%= render 'admin/shared/organization_header' %>

<div class="grid_8 admin-actions">
  <%= render 'admin/shared/organization_actions' %>
</div>

<div class="grid_12">
  <%= render 'admin/shared/organization_menu' %>
</div>

<div class="grid_8">
  <section>
    <%= form_for([:admin, @organization]) do |f| %>
      <legend>Organization Information</legend>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :address, 'Physical Address' %>
        <%= f.text_field :address %>
      </p>
      <p>
        <%= f.label :address_additional, 'Physical Address Line 2' %>
        <%= f.text_field :address_additional %>
      </p>
      <div class="grid_4 alpha">
      <p>
        <%= f.label :city %>
        <%= f.text_field :city %>
      </p>
      </div>
      <div class="grid_1">
      <p>
        <%= f.label :state %>
        <%= f.text_field :state %>
      </p>
      </div>
      <div class="grid_3 omega">
      <p>
        <%= f.label :zipcode %>
        <%= f.text_field :zipcode %>
      </p>
      </div>
      <legend>General Contact Information</legend>
      <p>
        <%= f.label :contact_name %>
        <%= f.text_field :contact_name %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
      </p>
      <p>
        <%= f.label :fax_number %>
        <%= f.text_field :fax_number %>
      </p>
      <legend>Reporting Information</legend>
      <p>
        <%= f.label :parent_organization %>
        <%= f.text_field :parent_organization %>
      </p>
      <p>
        <%= f.label :subsidizing_organization %>
        <%= f.text_field :subsidizing_organization %>
      </p>
      <p>
        <%= f.label :organizational_status %> <%= f.select :organizational_status, ArtsreadyDomain::ORGANIZATIONAL_STATUSES, :include_blank => true %>
      </p>
      <p>
        <%= f.label :operating_budget, "Last year my organization's operating budget was:"  %> <%= f.select :operating_budget, ArtsreadyDomain::OPERATING_BUDGETS, :include_blank => true %>
      </p>
      <p>
        <%= f.label :nsic_code, 'National Standard Institution Code' %>
        <%= f.select :nsic_code, ArtsreadyDomain::NSIC_CODES, :include_blank => true %> <br>
        <%= f.label :other_nsic_code, 'Enter other codes here:' %>
        <%= f.text_field :other_nsic_code %>
      </p>
    </fieldset>
      <%= f.submit 'Save Settings' %>
    <% end %>
  </section>
</div>

app/views/admin/organizations/index.html.erb
<div class="grid_12">
     <h1>Manage Organizations</h1>
  <section>
    <table class="resource side-nav-panels organizations">
      <thead>
        <tr>
          <th><p>Name</p></th>
          <th><p>Members</p></th>
          <th class="sorter-rfc822TimeOrNever"><p>Latest Activity</p></th>
          <th><p>Assessment %</p></th>
          <th><p>To-do %</p></th>
          <th><p>Status</p></th>
          <th><p>&nbsp;</p></th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each do |org| %>
          <tr>
            <td class="name"><p><%= org.name %></p></td>
            <td class="members"><p><%= link_to pluralize(org.users.count, 'member'), admin_organization_users_path(org) %> </p></td>
            <td class="activity"><p><%= rfc822_time(org.last_activity) || 'Never' %></p></td>
            <td class="assessment"><p><%= org.assessment_percentage_complete %>%</p></td>
            <td class="todo"><p><%= org.todo_percentage_complete %>%</p></td>
            <td class="status <%= org.status.to_sym %>"><p><%= org.status %></p></td>
            <td class="actions"><p>
              <%= link_to 'Edit', edit_admin_organization_path(org), :class => 'button' %>
            </p></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>