config/routes.rb
Artsready::Application.routes.draw do
  patch "/billing/cancel/(:id)" => "billing#cancel", :as => "billing_cancel"
  get "/billing/get_discount/(:code)" => "billing#get_discount"
  resource :billing, controller: 'billing'

  resources :payment_notifications, only: :create

  get "messages/create"
  get "needs/create"

  get "get_help" => "buddies#get_help", :as => "get_help"
  get "lend_a_hand" => "buddies#lend_a_hand", :as => "lend_a_hand"
  get "buddies" => "buddies#index", :as => "buddies"
  get "buddy(/:id)" => "buddies#show", :as => "buddy"
  get "buddies/profile"

  namespace :admin do
    get "/organizations/billing/(:id)" => "organizations#billing"
    get "/discount_codes/disabled" => "discount_codes#disabled"
    get "/discount_codes/usage" => "discount_codes#usage"
    get "/discount_codes/show_usage/(:id)" => "discount_codes#show_usage"
    patch "/organizations/allow_provisionary_access/(:id)" => "organizations#allow_provisionary_access"
    
    resources :organizations, :only => [:index, :edit, :update, :destroy] do
      resources :users, :only => [:index, :create, :destroy, :edit, :update]
      resources :subscription_events, except: :show
      resource :billing, controller: 'billing', only: [:edit, :update] do
        delete :cancel, on: :member
      end
      get 'billing', on: :member
    end
    resources :users, :only => [:index]
    resources :password_resets, :only => [:create]
    resources :articles, :only => [:update, :destroy, :index]
    resources :comments, :only => [:destroy]
    resources :messages, :only => [:destroy]
    resources :pages, except: [:show]
    resources :templates, only: [:index, :edit, :update]
    resources :questions
    resources :action_items
    resources :discount_codes, except: [:show, :destroy]
    resources :payment_variables
    root :to => 'home#dashboard', :as => "dashboard"
  end

  resources :articles do
    get 'critical_list', :on => :collection
    resources :comments, :only => [:create]
  end
  
  resources :resources
  resources :organizations, :only => [:edit, :update, :show, :new, :create] do
    resources :articles do
      get 'critical_list', :on => :collection
    end
    resources :crises, :only => [:index] do
      member do
        get 'summary'
      end
    end
    resources :battle_buddy_requests, :only => [:create, :show, :index, :update, :destroy]
    resources :messages, :only => [:create]
    resources :users
  end
  
  resources :crises do
    resources :updates
    resources :needs, :only => [:create, :edit, :update]
  end

  resources :archived_assessments, :only => [:index, :show]
  resource :assessment, :only => [:new, :create, :show] do
    resources :sections, :only => [:update]
  end
  resources :answers, :only => [:update] do
    member do
      put 'skip'
      put 'reconsider'
    end
  end
  
  resources :todos
  resources :todo_notes

  get "sign_up" => "organizations#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  post "sign_in" => "sessions#create"
  get "sign_out" => "sessions#destroy", :as => "sign_out"

  get 'confirm(/:id)' => 'password_resets#edit', :as => :confirmation
  
  resources :users, :only => [:new, :create, :edit, :update, :destroy]
  get "profile" => "users#profile", :as => "profile"
  
  resources :password_resets, :only => [:new, :create, :edit, :update]
  get "member/index", :as => "dashboard"
  get "member/library", :as => "library"

  # public pages
  get "page/:slug" => "pages#show", :as => "page"
  get '/offer' => 'pages#show', :slug => 'afta'

  get "readiness_library" => "home#readiness_library", :as => "readiness_library"
  get "home/public_articles" => "home#public_articles", :as => "public_articles"
  get "home/public_article(/:id)" => "home#public_article", :as => "public_article"
  get "news" => "home#news", :as => "news"
  root :to => "home#index"

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Name *', :class => 'required' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details, 'Details *', :class => 'required' %><br />
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= resource.details %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Details:</b>
  <%= @resource.details %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>